# we will convert the ../documentation/commands.md to a C header file
#
#

of = open("coreloop/lusee_commands.h", "w")
ofp = open ("pycoreloop/lusee_commands.py", 'w')
of.write("""
#ifndef LUSEE_SETTINGS_H
#define LUSEE_SETTINGS_H

// Master mode command for which everything below applies.
#define RFS_Settings 0x10
// Wait command for control, not recognized by the actual_coreloop
#define CTRL_WAIT 0XE0
"""
)

ofp.write("""
          
# This file is generated by scripts/create_cmd_include.py
# It includes all the commands that are available in the RFS_Settings mode
# generated from the documentation/commands.md file.

# Master CMD
RFS_SETTINGS = 0x10
CTRL_WAIT = 0XE0

# Commands
          """)

for line in open("documentation/lusee_commands.md"):
    line = line.split('|')
    if len(line)<4:
        continue
    offset, name, desc = line[1:4]
    name = name.strip()
    desc = desc.strip()
    if desc[-1]=='\n':
        desc = desc[:-1]
    print (offset, name, desc)
    if offset[:3] != " 0x":
        continue
    if "RFS_SET" not in name:
        continue
    of.write (f"// {desc}\n")
    of.write(f"#define {name} {offset}\n\n")
    ofp.write(f"# {desc}\n")
    ofp.write(f"{name} = {offset}\n\n")
    print (f'            case {name}:\n                cdi_not_implemented("{name}");\n                return;')

of.write("\n\n#endif")