name: Run uncrater tests

on:
  push:
    branches:
      - main
      - automate_uncrater

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Clone uncrater repo
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        owner: 'anigmetov'
        repository: 'uncrater'
        branch: 'main'
        access-token: ${{ secrets.UNCRATER_PAT }}

    - name: Compile coreloop library
      run: |
        mkdir build
        cd build
        cmake ..
        make -j cl_utils coreloop

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install packets
      run: |
        cd $GITHUB_WORKSPACE/uncrater
        pip install -r requirements.txt
    - name: Set CORELOOP_DIR environment variable
      run: echo "CORELOOP_DIR=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: Run test alive
      run: |
        cd $GITHUB_WORKSPACE/uncrater
        python test/cli_driver.py -r alive -b coreloop --skip-report
      env:
        CORELOOP_DIR: ${{ env.CORELOOP_DIR }}

    - name: Run test time_resolved
      run: |
        cd $GITHUB_WORKSPACE/uncrater
        python test/cli_driver.py -r time_resolved -b coreloop --skip-report
      env:
        CORELOOP_DIR: ${{ env.CORELOOP_DIR }}

    - name: Run test data_interface
      run: |
        cd $GITHUB_WORKSPACE/uncrater
        python test/cli_driver.py -r data_interface -b coreloop --skip-report
      env:
        CORELOOP_DIR: ${{ env.CORELOOP_DIR }}


    - name: Run standalon (pytest) encoding tests
      run: |
        cd $GITHUB_WORKSPACE/uncrater
        pytest test/standalone/test_encode_one_at_a_time.py
        pytest test/standalone/test_encode_shared_lz.py
      env:
        CORELOOP_DIR: ${{ env.CORELOOP_DIR }}

